---
- name: Build report containing list of applicable, installable, and installed errata
  hosts: localhost
  vars:
    credfile: ../private/creds.yml
    builder: ./errata-details.py
    sat_server: sat.example.com
    sat_user: SETME
    sat_password: SETME
    report_dir: ./tmp_final_report/
    errata_reports_dir: ./tmp_errata_reports/
    report_server: bastion.example.com
    report_server_installed_errata_path: /var/tmp/installed_errata_files/
    report_server_final_report_path: /var/tmp/final_reports/

  tasks:

    - name: Check for credentials file
      stat:
        path: "{{ credfile }}"
      register: stat_results

    - name: Define credentials using local file
      block:

      - name: Include variable definitions from local file
        include_vars:
          file: "{{ credfile }}"

      - name: Define Satellite credentials based on local file
        set_fact:
          sat_user: "{{ cf_sat_user }}"
          sat_password: "{{ cf_sat_password }}"

      when: stat_results.stat.exists

    - name: Define credentials using Ansible Tower custom credentials
      block:

      - name: Define Satellite credentials based on custom credential
        set_fact:
          sat_user: "{{ at_sat_user }}"
          sat_password: "{{ at_sat_password }}"

      when: not stat_results.stat.exists

    - name: Copy all of the installed errata reports from the report server
      command: "rsync -a {{ report_server }}:{{ report_server_installed_errata_path }} {{ errata_reports_dir }}"

    - name: Ensure final report directory is present (this is a local directory)
      file:
        path: "{{ report_dir }}"
        state: directory
      become: false

    - name: Run the report builder
      shell: "{{ builder }} -s {{ sat_server }} -u {{ sat_user }} -p {{ sat_password }} -l {{ report_dir }} -e {{ errata_reports_dir }} 2> /dev/null"

    - name: Copy the final report directory to the report server
      command: "rsync -a {{ report_dir }} {{ report_server }}:{{ report_server_final_report_path }}"
