---
- name: Gather installed errata from all hosts
#  hosts: foreman_content_view_rhel_7server
  hosts: "{{ target_host | default('NO_HOSTS')}}"
  remote_user: root
  vars:
    remote_report_dir: /var/tmp
    errata_reports_dir: ./errata_reports
    report_server: bastion.example.com
    report_server_installed_errata_path: /var/tmp/installed_errata_files/

  tasks:

  - name: Ensure errata reports directory is present (this is a local directory)
    file:
      path: "{{ errata_reports_dir }}"
      state: directory
    become: false
    delegate_to: localhost

  - name: Define report filename
    set_fact:
      report_filename: "{{ remote_report_dir }}/{{ ansible_host }}"
      
  - name: Get list of installed errata
#    shell: yum updateinfo list installed | awk 'NR>2 {errata[icnt++]=$0} END { for(ierrata=0; ierrata<icnt-1; ierrata++) {print errata[ierrata]}}'
    shell: yum updateinfo list installed
    register: installed_errata
    args:
      warn: no

#  - name: Debug
#    debug:
#      var: installed_errata.stdout

  - name: Write output to file
    copy:
      content: "{{ installed_errata.stdout }}"
      dest: "{{ report_filename }}"

  - name: Copy report to local directory
    fetch:
      dest: "{{ errata_reports_dir }}/"
      flat: Yes
      src: "{{ report_filename }}"

  - name: Remove report from remote system
    file:
      path: "{{ report_filename }}"
      state: absent

  - name: who am i
    command: whoami
    register: theuser
    delegate_to: localhost

  - name: debug
    debug:
      msg: "user is {{ theuser }}"
    delegate_to: localhost

  - name: Copy the installed errata reports over to the report server for further use
    remote_user: tprinz
    command: "rsync -a {{ errata_reports_dir }}/ {{ report_server }}:{{ report_server_installed_errata_path }}"
    delegate_to: localhost
