---
- name: Gather installed errata from all hosts
#  hosts: foreman_content_view_rhel_7server
  hosts: "{{ target_host | default('NO_HOSTS')}}"
#  remote_user: root
  become: true
  vars:
    remote_report_dir: /var/tmp
    installed_errata_reports_dir: /mnt/errata_info/installed_errata_reports

  tasks:

  - name: Ensure errata reports directory is present (this is a local directory)
    file:
      mode: 0777
      path: "{{ installed_errata_reports_dir }}"
      state: directory
    become: false
    delegate_to: localhost

  - name: Define report filename
    set_fact:
      report_filename: "{{ remote_report_dir }}/{{ ansible_host }}"
      
  - name: Get list of installed errata
    shell: yum updateinfo list installed
    register: installed_errata
    args:
      warn: no

  - name: Write output to file
    copy:
      content: "{{ installed_errata.stdout }}"
      dest: "{{ report_filename }}"

  - name: Copy report to local directory
    fetch:
      dest: "{{ installed_errata_reports_dir }}/"
      flat: Yes
      src: "{{ report_filename }}"

  - name: Remove report from remote system
    file:
      path: "{{ report_filename }}"
      state: absent
